---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nopCommerce-deploy
spec:
  minReadySeconds: 1
  replicas: 5
  selector:
    matchExpressions:
      - key: app 
        operator: In 
        values:
          - nopCommerce 
    strategy:
      type: RollingUpdate
      rollingUpdate: 
        maxSurge: 20%
        maxUnavailable: 20%
    template:
      metadata:
        labels:
          app: nopCommerce
          purpose: practice 
      spec: 
        containers:
          - name: nopCommerce-container
            image: nikhitaa/nopcommerce:1.0
            resources:
              limits:
                cpu: 500m
                memory: 256Mi
            ports:
              - containerPort: 5000
                protocol: TCP
            livenessProbe:
              httpGet: 
                path: /
                port: 5000
            readinessProbe:
              httpGet:
                path: /orders
                port: 5000
        initContainers: 
          - name: mysql-container
            image: mysql:8
            env:
              - name: MYSQL_ROOT_PASSWORD
                value: mysqlroot@123
              - name: MYSQL_DATABASE
                value: mysql-nop
            
            
      