---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nopCommerce-deploy
spec:
  minReadySeconds: 1
  replicas: 5
  selector:
    matchExpressions:
      - key: app 
        operator: In 
        values:
          - nopCommerce 
    strategy:
      type: RollingUpdate
      rollingUpdate: 
        maxSurge: 20%
        maxUnavailable: 20%
    template:
      metadata:
        labels:
          app: nopCommerce
          purpose: practice 
      spec: 
        initContainers:
          - name: nopCommerce-container
            image: nikhitaa/nopcommerce:1.0
            resources:
              cpu: 500m
              memory: 128Mi
            ports:
              - containerPort: 5000
                protocol: TCP
            livenessProbe:
              httpGet: 
                path: /
                port: 5000
        containers: 
          - name: mysql-container
            image: mysql:8
            ports:
              - containerPort: 3306
                protocol: TCP
            resources:
              cpu: 250m
              memory: 256Mi
            readinessProbe:
              httpGet:
                path: /orders
                port: 3306
        
      